- name: condition checking
  hosts: server2
  tasks:
  - name: installing nginx
    dnf:
      name: nginx
      state: present
    when:
    - ansible_distribution == 'AlmaLinux'
    - ansible_os_family == 'RedHat'
  - name: Enable and Start nginx
    service:
      name: nginx
      enabled: yes
      state: started
    when:
    - ansible_distribution == 'AlmaLinux'
    - ansible_os_family == 'RedHat'
