- name: Condition checking
  hosts: server3
  tasks:
    - name: Installing apache2
      apt:
        name: apache2
        state: present
      when:
      - ansible_distribution == 'Ubuntu'
      - ansible_os_family == 'Debian'
    - name: Enable and Start apache2
      service:
        name: apache2
        enabled: yes
        state: started
      when:
      - ansible_distribution == 'Ubuntu'
      - ansible_os_family == 'Debian'
